### ISSUE TITLE
Can't setup duell

### ISSUE THREAD

**Issue by linkocrn** [gameduell/duell#15]
I am trying to setup duell on Windows but keep becoming this error: http://i.imgur.com/Q3s2DHc.png

**Comment by Khaledgarbaya** [comment]
Hi,
Can you please run the the command again and add -verbose to it so we can get more details
`haxelib run duell self_setup -verbose`
Best,
Khaled

**Comment by Khaledgarbaya** [comment]
cc @catdawg

**Comment by linkocrn** [comment]
Hi Khaled,

This is what I have with -verbose: http://i.imgur.com/6NuQwAc.png

**Comment by Khaledgarbaya** [comment]
Try to clone the repo list manually 
`git clone git@github.com:gameduell/duell-repository-list.git` and check if everything is fine with your ssh key

**Comment by linkocrn** [comment]
It looks like I don't have the permission for it: http://i.imgur.com/BMzyj5T.png

**Comment by Khaledgarbaya** [comment]
you just need to setup ssh key in your pc and add it to your github account, https://help.github.com/articles/generating-ssh-keys/

**Comment by linkocrn** [comment]
That worked, thanks a lot !
